### ISSUE TITLE
Downloading dataset issue 

### ISSUE THREAD

**Issue by kkddhh386** [bipashasen/INRV#1]
When I try to download How2Sign-Faces dataset using downloadable link in "Getting started", I can not enter the download link.
Could you tell me another link to download the dataset?

**Comment by bipashasen** [comment]
It is a downloadable link, that is, the download should start in your browser as soon as you click on it. Otherwise, you can also go to [http://cvit.iiit.ac.in/images/datasets/inrv/How2Sign-Blobs.tar](http://cvit.iiit.ac.in/images/datasets/inrv/How2Sign-Blobs.tar) and download (check your downloads tab in the browser, it should start).
